version: '3'

services:
  nest_api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: api:latest
    container_name: api
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres_db
    restart: always
    volumes:
      - ./:/app/src
      - /app/node_modules
    networks:
      - custom-database-network
  
  postgres_db:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    image: db:latest
    container_name: db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-logs:/var/log/postgresql
    networks:
      - custom-database-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

volumes:
  postgres-data:
  postgres-logs:

networks:
  custom-database-network:
    driver: bridge